parameters:
#    ft_swagger.example.class: FT\SwaggerBundle\Example

services:
#    ft_swagger.example:
#        class: %ft_swagger.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
