api_exercises:
    resource: "@FTApiBundle/Resources/config/routing/exercises.yml"

api_workouts:
    resource: "@FTApiBundle/Resources/config/routing/workouts.yml"

api_users:
    resource: "@FTApiBundle/Resources/config/routing/users.yml"

api_security:
    resource: "@FTApiBundle/Resources/config/routing/security.yml"
