api_exercises:
    resource: "@FTApiBundle/Resources/config/routing/exercises.yml"

api_sets:
    resource: "@FTApiBundle/Resources/config/routing/sets.yml"

api_workouts:
    resource: "@FTApiBundle/Resources/config/routing/workouts.yml"

api_users:
    resource: "@FTApiBundle/Resources/config/routing/users.yml"
