parameters:
    ft_api.apitoken_user_provider.class: FT\ApiBundle\Security\ApiTokenUserProvider
    ft_api.apitoken_authenticator: FT\ApiBundle\Security\ApiTokenAuthenticator
    ft_api.manager.api_token.class: FT\ApiBundle\Manager\ApiTokenManager

services:
    ft_api.apitoken_user_provider:
        class: %ft_api.apitoken_user_provider.class%
        arguments: ["@doctrine.orm.entity_manager"]

    ft_api.apitoken_authenticator:
        class: %ft_api.apitoken_authenticator%
        arguments: ["@ft_api.apitoken_user_provider"]

    ft_api.manager.api_token:
        class: %ft_api.manager.api_token.class%
        arguments: ["@doctrine.orm.entity_manager"]
