users_sign_up:
    path: /sign_up
    methods: [GET]
    defaults:
        _controller: "FTFrontBundle:User:signup"

users_sign_in:
    path: /sign_in
    methods: [GET]
    defaults:
        _controller: "FTFrontBundle:User:signin"

users_sign_out:
    path: /sign_out

users_auth:
    path: /auth

users:
    path: /
    methods: [GET]
    defaults:
        _controller: "FTFrontBundle:User:index"

users_create:
    path: /
    methods: [POST]
    defaults:
        _controller: "FTFrontBundle:User:create"

users_follow:
    path: /{username}/following
    methods: [POST]
    defaults:
        _controller: "FTFrontBundle:User:follow"

users_unfollow:
    path: /{username}/following
    methods: [PATCH]
    defaults:
        _controller: "FTFrontBundle:User:unfollow"

users_show:
    path: /{username}
    methods: [GET]
    defaults:
        _controller: "FTFrontBundle:User:show"
