ft_front:
    resource: "@FTFrontBundle/Resources/config/routing.yml"
    prefix:   /

ft_api:
    resource: "@FTApiBundle/Resources/config/routing.yml"
    prefix:   /api/1

ft_swagger:
    resource: "@FTSwaggerBundle/Resources/config/routing.yml"
    prefix:   /api/swagger
