parameters:
    ft_exercise.entity.exercise.class: FT\ExerciseBundle\Entity\Exercise
    ft_exercise.entity.exercise_parameter.class: FT\ExerciseBundle\Entity\ExerciseParameter

    ft_exercise.manager.exercise.class: FT\ExerciseBundle\Manager\ExerciseManager
    ft_exercise.manager.exercise_parameter.class: FT\ExerciseBundle\Manager\ExerciseParameterManager

services:
    ft_exercise.manager.exercise:
        class: %ft_exercise.manager.exercise.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %ft_exercise.entity.exercise.class%

    ft_exercise.manager.exercise_parameter:
        class: %ft_exercise.manager.exercise_parameter.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %ft_exercise.entity.exercise_parameter.class%
