<?php

namespace FT\WorkoutBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutRepository extends EntityRepository
{
    public function findAllLimited($limit, $offset)
    {
        $dql = 'SELECT w FROM FTWorkoutBundle:Workout w';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }
}
