api_exercises_index:
    path: /exercises.{_format}
    methods: [GET]
    defaults:
        _controller: FTApiBundle:Exercise:index
        _format: json
    requirements:
        _format: json|xml

api_exercises_create:
    path: /exercises.{_format}
    methods: [POST]
    defaults:
        _controller: FTApiBundle:Exercise:create
        _format: json
    requirements:
        _format: json|xml

api_exercises_read:
    path: /exercises/{id}.{_format}
    methods: [GET]
    defaults:
        _controller: FTApiBundle:Exercise:read
        _format: json
    requirements:
        _format: json|xml
        id: \d+

api_exercises_update:
    path: /exercises/{id}.{_format}
    methods: [PUT,PATCH]
    defaults:
        _controller: FTApiBundle:Exercise:update
        _format: json
    requirements:
        _format: json|xml
        id: \d+

api_exercises_delete:
    path: /exercises/{id}.{_format}
    methods: [DELETE]
    defaults:
        _controller: FTApiBundle:Exercise:delete
        _format: json
    requirements:
        _format: json|xml
        id: \d+

api_exercise_parameters_index:
    path: /exercises/{id}/parameters.{_format}
    methods: [GET]
    defaults:
        _controller: FTApiBundle:ExerciseParameter:index
        _format: json
    requirements:
        _format: json|xml
        id: \d+

api_exercise_parameters_read:
    path: /exercises/{exercise_id}/parameters/{id}.{_format}
    methods: [GET]
    defaults:
        _controller: FTApiBundle:ExerciseParameter:read
        _format: json
    requirements:
        _format: json|xml
        exercise_id: \d+
        id: \d+

api_exercise_parameters_create:
    path: /exercises/{exercise_id}/parameters.{_format}
    methods: [POST]
    defaults:
        _controller: FTApiBundle:ExerciseParameter:create
        _format: json
    requirements:
        _format: json|xml
        exercise_id: \d+

api_exercise_parameters_update:
    path: /exercises/{exercise_id}/parameters/{id}.{_format}
    methods: [PUT, PATCH]
    defaults:
        _controller: FTApiBundle:ExerciseParameter:update
        _format: json
    requirements:
        _format: json|xml
        exercise_id: \d+
        id: \d+

api_exercise_parameters_delete:
    path: /exercises/{exercise_id}/parameters/{id}.{_format}
    methods: [DELETE]
    defaults:
        _controller: FTApiBundle:ExerciseParameter:delete
        _format: json
    requirements:
        _format: json|xml
        exercise_id: \d+
        id: \d+
