parameters:
    ft_user.manager.user.class: FT\UserBundle\Manager\UserManager

services:
    ft_user.manager.user:
        class: %ft_user.manager.user.class%
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory]
