<?php

namespace FT\ExerciseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends EntityRepository
{
    public function findAllLimited($limit, $offset)
    {
        $dql = 'SELECT e FROM FTExerciseBundle:Exercise e';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }

    /**
     * @TODO: Add limit and offset
     *
     * @param  array $ids
     * @return array
     */
    public function findAllByIds(array $ids)
    {
        $dql = 'SELECT e FROM FTExerciseBundle:Exercise e
                WHERE e.id IN (:ids)';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('ids', $ids)
            ->getResult();
    }
}
