<?php

namespace FT\ExerciseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseSetRepository extends EntityRepository
{
    public function findAllLimited($limit, $offset)
    {
        $dql = 'SELECT e FROM FTExerciseBundle:ExerciseSet e';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }

    public function findAllByWorkout($workout)
    {
        $dql = 'SELECT e FROM FTExerciseBundle:ExerciseSet e
                WHERE e.workout = :workout';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('workout', $workout)
            ->getResult();
    }
}
