<?php

namespace FT\ExerciseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseParameterValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseParameterValueRepository extends EntityRepository
{
}
