<?php

namespace FT\ExerciseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseParameterRepository extends EntityRepository
{
    public function findAllLimited($limit, $offset)
    {
        $dql = 'SELECT ep FROM FTExerciseBundle:ExerciseParameter ep';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }
}
