ft_front_exercises:
    resource: "@FTFrontBundle/Resources/config/routing/exercise.yml"
    prefix:   /exercises

ft_front_workouts:
    resource: "@FTFrontBundle/Resources/config/routing/workout.yml"
    prefix:   /workouts
