parameters:
#    ft_front.example.class: FT\FrontBundle\Example

services:
#    ft_front.example:
#        class: %ft_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
