<?php

namespace FT\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTokenRepository extends EntityRepository
{
    /**
     * Find one ApiToken by token string
     *
     * @param $token
     * @return mixed
     */
    public function findOneByTokenString($token)
    {
        $dql = 'SELECT t FROM FTApiBundle:ApiToken t
                WHERE t.token = :token';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('token', $token)
            ->getOneOrNullResult();
    }

    /**
     * Find all tokens for User
     *
     * @param $user
     * @return array
     */
    public function findAllByUser($user)
    {
        $dql = 'SELECT t FROM FTApiBundle:ApiToken t
                WHERE t.user = :user';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('user', $user)
            ->getResult();
    }
}
