<?php

namespace FT\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $limit
     * @param $offset
     * @return array
     */
    public function findAllLimited($limit, $offset)
    {
        $dql = 'SELECT u FROM FTUserBundle:User u';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }
}
